import { z } from 'zod'

export const EthnicitySchema = z.enum(['CAUCASIAN', 'LATINA', 'ASIAN', 'ARABIC', 'BLACK', 'INDIAN'])

export const EyeColorSchema = z.enum(['BROWN', 'BLUE', 'GREEN', 'YELLOW', 'RED'])

export const HairStyleSchema = z.enum([
	'STRAIGHT',
	'BRAIDS',
	'BANGS',
	'CURLY',
	'BUN',
	'SHORT',
	'LONG',
	'PONYTAIL',
	'PIGTAILS',
	'BUZZ_CUT',
	'SLIC_BACK',
	'MAN_BUN',
	'DREADLOCKS',
	'BALD',
])

export const HairColorSchema = z.enum([
	'BLACK',
	'BRUNETTE',
	'BLONDE',
	'PINK',
	'REDHEAD',
	'GREEN',
	'BROWN',
	'GINGER',
	'GRAY',
	'WHITE',
])

export const BodyTypeSchema = z.enum(['FIT', 'SKINNY', 'MUSCULAR', 'CHUBBY', 'SLIM', 'WIDE'])

export const PersonalitySchema = z.enum([
	'CAREGIVER',
	'SAGE',
	'INNOCENT',
	'JESTER',
	'TEMPTRESS',
	'DOMINANT',
	'SUBMISSIVE',
	'LOVER',
	'NYMPHO',
	'MEAN',
	'CONFIDANT',
	'EXPERIMENTER',
	'PROTECTOR',
	'HERO',
	'TOY_BOY',
	'BEAST',
	'REBEL',
	'SCHOLAR',
])

export const OccupationSchema = z.enum([
	'TEACHER',
	'NURSE',
	'INTERIOR_DESIGNER',
	'BEAUTY_THERAPIST',
	'STUDENT',
	'SOLDIER',
	'STEWARDESS',
	'CHEF',
	'PHOTOGRAPHER',
	'MODEL',
	'ACTRESS',
	'LIBRARIAN',
	'NUTRITIONIST',
	'FLORIST',
	'WEDDING_PLANNER',
	'FASHION_BLOGGER',
	'YOGA_INSTRUCTOR',
	'CHILDCARE_WORKER',
	'SOCIAL_WORKER',
	'EXECUTIVE_ASSISTANT',
	'EVENT_COORDINATOR',
	'MAKEUP_ARTIST',
	'ART_TEACHER',
	'DANCE_INSTRUCTOR',
	'BOUTIQUE_OWNER',
	'JEWELRY_MAKER',
	'PERFUMER',
	'VOICE_COACH',
	'PASTRY_CHEF',
	'PILATES_INSTRUCTOR',
	'HAIRSTYLIST',
	'DRAG_PERFORMER',
	'FLORAL_DESIGNER',
	'THERAPIST',
])

export const RelationshipSchema = z.enum([
	'STRANGER',
	'SCHOOL_MATE',
	'COLLEAGUE',
	'MENTOR',
	'GIRLFRIEND',
	'SEX_FRIEND',
	'WIFE',
	'MISTRESS',
	'FRIEND',
	'BEST_FRIEND',
	'STEP_SISTER',
	'STEP_MOM',
	'BOYFRIEND',
	'HUSBAND',
	'STEP_BROTHER',
	'STEP_DAD',
])

export const SpecialFeaturesSchema = z.enum([
	'PUBIC_HAIR',
	'PREGNANT',
	'GLASSES',
	'FRECKLES',
	'TATTOOS',
	'BELLY_PIERCINGS',
	'NIPPLE_PIERCINGS',
])

export const HobbySchema = z.enum([
	'FITNESS',
	'VLOGGING',
	'TRAVELING',
	'HIKING',
	'GAMING',
	'PARTYING',
	'ANIME',
	'COSPLAY',
	'WRITING',
	'DIY_CRAFTING',
	'PHOTOGRAPHY',
	'VOLUNTEERING',
	'CARS',
	'ART',
	'WATCHING_NETFLIX',
	'MANGA_AND_ANIME',
	'MARTIAL_ARTS',
	'BAKING',
	'READING',
	'PAINTING',
	'KNITTING',
	'YOGA',
	'SURFING',
	'PLAYING_PIANO',
	'BIRD_WATCHING',
	'SKATEBOARDING',
	'POTTERY',
	'STAND_UP_COMEDY',
	'ASTROLOGY',
	'MOUNTAIN_BIKING',
	'SCUBA_DIVING',
	'SALSA_DANCING',
	'ANTIQUING',
	'CALLIGRAPHY',
	'HORSEBACK_RIDING',
	'ARCHERY',
	'CHESS',
	'CYCLING',
	'INTERIOR_DECORATING',
	'GARDENING',
	'DANCING',
	'EVENT_PLANNING',
	'COOKING',
	'MECHANIC',
	'ASTRONOMY',
	'FLIRTING',
	'SWIMMING',
	'PILATES',
])

export const ClothingSchema = z.enum([
	'BIKINI',
	'SKIRT',
	'CHEERLEADER_OUTFIT',
	'PENCIL_DRESS',
	'LONG_DRESS',
	'WOMENS_BASKETBALL_JERSEY',
	'SOCCER_UNIFORM',
	'TENNIS_OUTFIT',
	'SWIMSUIT',
	'SPORTSWEAR',
	'WEDDING_DRESS',
	'FANCY_DRESS',
	'WITCH_COSTUME',
	'SUMMER_DRESS',
	'LINGERIE',
	'LATEX_OUTFIT',
	'SCHOOL_UNIFORM',
	'YOGA_OUTFIT',
	'LEATHER_OUTFIT',
	'PRINCESS_DRESS',
	'CORSET',
	'ANGEL_COSTUME',
	'MAID_OUTFIT',
	'MEDIEVAL_ARMOR',
	'LAB_COAT',
	'COWBOY_ATTIRE',
	'CARNIVAL_COSTUME',
	'CASUAL_WEAR',
	'NURSE_UNIFORM',
	'SANTA_CLAUS_OUTFIT',
	'POLICE_UNIFORM',
	'STEAMPUNK_GEAR',
	'SUPERHERO_COSTUME',
	'TEACHERS_ATTIRE',
	'VIKING_COSTUME',
	'FIREFIGHTER_GEAR',
	'MILITARY_UNIFORM',
	'CONSTRUCTION_OUTFIT',
	'LONG_COAT',
	'HOODIE',
	'JEANS',
	'LEGGINGS',
	'NINJA_OUTFIT',
	'PAJAMAS',
	'CLOWN_COSTUME',
	'FLIGHT_ATTENDANT_UNIFORM',
	'BARISTA_OUTFIT',
	'BELLY_DANCER_COSTUME',
	'GOTH_ATTIRE',
	'PIRATE_COSTUME',
	'PRISONER_OUTFIT',
	'RACE_DRIVER_SUIT',
	'HIJAB',
	'TUTU',
	'PONCHO',
	'HIP_HOP_ATTIRE',
	'SKATEPARK_GEAR',
	'LUMBERJACK_OUTFIT',
	'ADVENTURER_GEAR',
	'SAILOR_UNIFORM',
	'GOLF_ATTIRE',
	'ONESIE',
	'OVERSIZED_SHIRT',
	'TRIBAL_ATTIRE',
	'SECRETARY_OUTFIT',
	'POP_STAR_COSTUME',
	'SUIT_AND_SHIRT',
	'JEANS_AND_TSHIRT',
	'CHINOS_AND_SHIRT',
	'BERMUDA_AND_POLO',
	'PANTS_AND_SWEATER',
	'TRACKSUIT',
	'BLAZER_AND_TSHIRT',
	'HOODIE_AND_CARGO',
	'DENIM_AND_KHAKIS',
	'CARDIGAN_AND_SHIRT',
	'PEACOAT_AND_TURTLENECK',
	'VEST_AND_LONG_SLEEVE',
	'TRENCH_AND_COLLARED_SHIRT',
	'JACKET_AND_CHINOS',
	'POLO_AND_LINEN_PANTS',
	'SHIRT_AND_CORDUROY_PANTS',
	'SUIT_AND_TIE',
	'TUXEDO',
	'SHORTS_AND_HENLEY',
	'HENLEY_AND_SHORTS',
	'LINEN_SHIRT_AND_PANTS',
	'RUGBY_SHIRT_AND_JOGGERS',
	'SWIM_SHORTS',
	'TEE_AND_LEATHER_PANTS',
	'MILITARY',
	'FIREFIGHTER',
	'POLICE',
	'F1_DRIVER',
	'MARTIAL_ARTS_BLACK_BELT',
	'PILOT',
	'WAITER',
	'CHEF',
	'BARISTA',
	'BUILDER',
	'STEAMPUNK',
	'ASTRONAUT',
	'HIP_HOP',
	'GOTHIC',
	'PIRATE',
	'SCOTTISH',
	'PRINCE',
	'MONK',
	'PRISONER',
	'SANTA',
	'SAMURAI',
	'BASKETBALL',
	'SOCCER',
	'TENNIS',
	'RUGBY',
	'GOLFER',
	'SURFER',
	'SKI',
	'LUMBERJACK',
	'BIKER',
	'COWBOY',
	'SCIENTIST',
	'NINJA',
	'KNIGHT',
])

export const GenderSchema = z.enum(['FEMALE', 'MALE'])

export const ChatModelSchema = z.object({
	name: z.string().min(2, { message: 'Name must be at least 2 characters long' }),
	age: z.number().int().min(18).max(100),
	slug: z.string().regex(/^[a-z0-9-]+$/, { message: 'Slug must be lowercase, numbers, and hyphens only' }),
	avatar: z.string().url(),
	about: z.string().optional(),

	ethnicity: EthnicitySchema,
	eyeColor: EyeColorSchema,
	hairStyle: HairStyleSchema,
	hairColor: HairColorSchema,
	bodyType: BodyTypeSchema,

	personality: z.array(PersonalitySchema).min(1, { message: 'At least one personality is required' }),
	occupation: OccupationSchema,
	relationship: RelationshipSchema,

	specialFeatures: z.array(SpecialFeaturesSchema).optional(),
	hobbies: z.array(HobbySchema).min(1, { message: 'At least one hobby is required' }),
	clothing: ClothingSchema,

	gender: GenderSchema,

	// Optional gender-specific fields
	breastSize: z.string().optional(),
	buttSize: z.string().optional(),
	dickSize: z.string().optional(),
})

// Type for creating a new model (input)
export type ChatModelCreateInput = z.infer<typeof ChatModelSchema>

// Example of creating a validation function
export function validateModel(data: unknown): ChatModelCreateInput {
	return ChatModelSchema.parse(data)
}
