import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/header'

const onest = Onest({
	variable: '--font-onest',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${onest.className} antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
					<div className="w-full h-full">
						<Header />
						<div className="mt-8">
							<aside className="transition z-[1100] fixed top-[60px] h-[calc(100vh-60px)] bg-background border-r border-r-accent left-0 w-[250px] lg:w-[230px] flex flex-col p-4 pb-[60px] lg:pb-4 font-medium text-muted-foreground -translate-x-full lg:translate-x-0"></aside>
							<div className="w-full lg:pl-[230px]">{children}</div>
						</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	)
}
